### ISSUE TITLE
Ft. Request: Add $page parameter to get_page_excerpt function

### ISSUE THREAD

**Issue by webketje** [GetSimpleCMS/GetSimpleCMS#1055]
Getting a page excerpt is most relevant to use when exactly not on that page.

**Comment by tablatronix** [comment]
`get_page_excerpt` is a theme function so we will leave as is.
I'll create an internal function for getting page stuff including this.

**Comment by webketje** [comment]
I guess ultimately this boils down to whether you consider blog functionality to be theme- or plugin-bound.. I would say plugin as well, but still I can't possibly think of any use-case for this function..

**Comment by cnb** [comment]
maybe for `og:description` or things like that...

**Comment by tablatronix** [comment]
I have no idea, but it's not a new function, its since 2.0, so it doesn't matter.

**Comment by HelgeSverre** [comment]
I needed functionality like this when i wanted to auto-generate a "Services" page from the page excerpt of all child pages under a "Services" page, I had to do it manually by parsing the xml files and such instead of using a function like this, I'd very much welcome functions that grabs a arbitrary page's excerpt/content/anything for used in more "advanced" themes.

**Comment by cnb** [comment]
```php
getPageContent($page); // display content

echo getExcerpt(returnPageContent($page)); // display excerpt with default options
```

**Comment by tablatronix** [comment]
I added it as a basic wrapper, if you want advanced stuff like get_page_excerpt you will need to do that on your own, as most filters for content assume they are being called for the current page and might not work properly when called on arbitrary page content. We also perform strips on it, so we might want to add that in also.
