### ISSUE TITLE
Update admin UI design?

### ISSUE THREAD

**Issue by CodeCharming** [GetSimpleCMS/GetSimpleCMS#1080]
I've been customizing the admin UI style for a design agency I'm working with. I updated it to a modern, flat design look with solid colors, no gradients, square edges instead of rounded ones, and slightly larger easy-to-read font sizes. It's not much but I think it would make a good addition the project. Is someone already working on this or should I contribute my CSS changes?

**Comment by webketje** [comment]
See also: [Modern admin](http://get-simple.info/extend/plugin/modern-admin/811/) plugin & [FlatBlue] Admin Theme

**Comment by CodeCharming** [comment]
Thanks. Is the plugin method the preferred way of changing the admin panel design?

**Comment by tablatronix** [comment]
The only preferred way is the very limited, admin.xml colors, the others are mostly new projects members have created ,but they are all essentially hacked in styles, the back end is not very openly themeable in it current version.

There is also this

http://get-simple.info/extend/plugin/adminxml-plus/946/
and
this
http://get-simple.info/extend/plugin/custom-admin-css/15/

That people have traditionally used to override the backend styles.

It will be several versions until the backend code and presentation are separated into modern standards so that is can be pluggable.

**Comment by tablatronix** [comment]
Of course you could always fork GS if your changes are extreme and create a new branch for your changes, this way merging updates will be easy. But for sharing the style overrides is the best option.

**Comment by tablatronix** [comment]
3.4 will have some style hooks to append additional styles directly....
#859 

But the structure is still pretty dated and patchworked making some overrides hard to do, eventually it all has to be redone, and all non function code removed from `admin/template/`

**Comment by CodeCharming** [comment]
Alright, thanks!
