### ISSUE TITLE
update cke 4.5.9 - ckeditor cache problem

### ISSUE THREAD

**Issue by tablatronix** [GetSimpleCMS/GetSimpleCMS#1155]
ckeditor finally fixed the issue with icons.png caching.

**Comment by cnb** [comment]
I don't see the new `GSCKETSTAMP` setting in the changelog.

If I'm not mistaken, default is true (to use the GS version as timestamp), false to disable, or else use a custom string.

I'd like to know because I'm using it for next NM version ( https://github.com/cnb/News_Manager-getsimplecms/issues/252 )

(Also for adding it to the wiki when 3.3.10 is released)

**Comment by tablatronix** [comment]
I have not decided if it will be in userspace but want everything to have a definition going forward.

**Comment by tablatronix** [comment]
but yes that syntax is correct

**Comment by tablatronix** [comment]
added definition
```
// define ckeditor timestamp query string cache control, true uses gs verdsion, false none, or custom string
# define(`CKETSTAMP`,false)

**Comment by tablatronix** [comment]
#982
