### ISSUE TITLE
Lowercased components and snippets names

### ISSUE THREAD

**Issue by dimayakovlev** [GetSimpleCMS/GetSimpleCMS#1165]
Is it feature or bug in 3.4? Components and snippets names automatically converts to lowercase after leaving input field. For example, type in name "Custom Component" and it will be converted to "custom component".

**Comment by tablatronix** [comment]
Yes its a bug

**Comment by tablatronix** [comment]
I was considering it a feature until i could decide on how to deal with this, the problem now is that the slugs are hidden and the titles are arbitrary, and the ids are generated from the titles.

So what happens when you add a slug like

Sidebar#4
Sidebar4

They both could get the same slug after submission and cleaning, I also got stuck in a situation where  I had 2 components with identical titles, but different slugs.

It was very confusing.

I have made changes to avoid some of this but it is still odd.

I also thought about having component ID and a title field, or desc field to put whatever you want in, and having the 2 have nothing to do with each other.

**Comment by tablatronix** [comment]
other bugs
- [ ]  compslug& leaves you with a blank slug in xml

**Comment by tablatronix** [comment]
I just realized that xml objects are passed by identifier by default, doh so addComponentItem(&$xml essentially 😕

**Comment by tablatronix** [comment]
please test out ajax saving for a bit ( refresh after save to make sure it saved )
I had some problems and spent a ton of time debugging, then it just started working again , so i have no idea wtf happened.

**Comment by dimayakovlev** [comment]
No problems with names. :)
I found that deleting components may be confusing. User clicks on x button and confirms deletion, notification says about successfull deletion. But actually component will be deleted only after click on Save Components button.

**Comment by dimayakovlev** [comment]
Confirmation message doesn't include name of newly created component.

**Comment by tablatronix** [comment]
Component deletion has always been like that at leadt now its greyed out so you know also you cant navigate away until you save

**Comment by tablatronix** [comment]
I think i have notes on this in the component refactor issue. 
Not sure the best way to ui that

**Comment by dimayakovlev** [comment]
May be add message about necessary to click on Save Components button to apply changes?

**Comment by tablatronix** [comment]
#624
